### PR TITLE
Fill opacity for SVGPathBuilder

### PR DESCRIPTION
**Pull request by Gulvan0**

### CODE REVIEW

**Comment by ianharrigan** [comment]
```
./haxe/ui/backend/html5/svg/SVGPathBuilder.hx:120: characters 49-66 : Null<Float> should be String
./haxe/ui/backend/html5/svg/SVGPathBuilder.hx:120: characters 49-66 : Float should be String
./haxe/ui/backend/html5/svg/SVGPathBuilder.hx:120: characters 49-66 : For function argument 'value'
```

**Comment by ianharrigan** [comment]
https://github.com/haxeui/haxeui-html5/actions/runs/3882441518/jobs/6622596592

**Comment by ianharrigan** [comment]
ill check it out in a bit

**Comment by Gulvan0** [comment]
#40

**Pull request merged**
